EOY_WEBapp/Controllers/LoginController.cs
using EOY_WEBapp.Models;
using EOY_WEBapp.Data;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using RestSharp;
using System.Text.Json;
using NuGet.Packaging;
using System.Collections.Generic;

namespace EOY_WEBapp.Controllers
{
	public class LoginController : Controller
	{
		private readonly EOY_Values _values = new EOY_Values();
		private readonly EOY_Functions _fce = new EOY_Functions();

		private readonly ILogger<LoginController> _logger;

		public LoginController(ILogger<LoginController> logger)
		{
			_logger = logger;
		}


		public IActionResult Index()
		{
           
            return View();

		}

		[HttpPost]
		public async Task<IActionResult> Index(LoginModel loginModel)
		{

			try
			{
				var myClient = new RestClient(_fce.UniversalApiAdress("FindUser"));
				var request = new RestRequest();
				request.AddQueryParameter("username", loginModel.Username);
				request.AddQueryParameter("password", loginModel.Password);
				var response = myClient.Get(request);
				var content = response.Content;
				var user =  JsonSerializer.Deserialize<List<LoginModel>>(content);
				var userdata = user.FirstOrDefault();
				if(user != null)
				{
                    if (user.Count() == 1)
                    {
                        TempData["Fullname"] = userdata.FullName;
                        return RedirectToAction("Index", "Home"); // Přesměrování na domovskou stránku
                    }
                }
			}
			catch (Exception e)
			{
				// Zde byste měli zalogovat chybu
				ModelState.AddModelError("", "Došlo k chybě při přihlašování.");

			}

			return  View(); // Znovu zobrazit přihlašovací formulář s chybami (pokud jsou)
		}

		

	}
}

EOY_WEBapp/Controllers/ReportController.cs
using EOY_WEBapp.Data;
using EOY_WEBapp.Dto;
using EOY_WEBapp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.Project;
using RestSharp;
using System.Text.Json;

namespace EOY_WEBapp.Controllers
{
    public class ReportController : Controller
    {
        private readonly EOY_Functions _fce = new EOY_Functions();

        public async Task<IActionResult> Index()
        {
            var result = await _fce.EOYrestResponse<IssueModels>(EOY_Values.HISTORY_ERRORS_CONTROLLER, EOY_Values.GET);
            return View(result);

        }
        public IActionResult Create()
        {
            return View("Create");
        }
           


    }
}

EOY_WEBapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EOY_WEBapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/styleLayout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EOY_WEBapp.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <div class="item">
            <h1>Logo Firmy</h1>
        </div>
        <div class="item right">
            @{
                var user = TempData["Fullname"] as string;
                <p>@user</p> @*Zde potřebuji propsat jmeno uživatele*@
            }
           
            @Html.ActionLink("Odhlásit", "Index", "Login", null, null)
        </div>
    </header>
    
    <nav>
        @Html.ActionLink("Sledovací panel", "Index","Home", null, new { @class="a-link" })
        <div class="subnav">
            <button class="subnavbtn">Reporty <i class="fa fa-caret-down"></i></button>
            <div class="subnav-content">
                @Html.ActionLink("Aktualní statistika", "Index","Report",null, new { @class="a-link" })
            </div>
        </div>
        <div class="subnav">
            <button class="subnavbtn">Nastavení <i class="fa fa-caret-down"></i></button>
            <div class="subnav-content">
                @Html.ActionLink("Správa uživatelů", "Index","Account",null, new { @class="a-link" })
                @Html.ActionLink("Správa pracovníků", "IndexWorker","Worker",null, new { @class="a-link" })
            </div>
        </div>
    </nav>

    <main>
        @RenderBody()
    </main>

    <footer class="border-top footer">
        <img src="~/Pictures/eoyLogo.png" alt="EOY-Logo" width="100px" />
        <p style="float:right;">Vytvořeno těmi nejlepšími</p>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>